### ISSUE TITLE
size mismatch error when running merge_lora.py

### ISSUE THREAD

**Issue by jl3676** [allenai/open-instruct#190] opened 2024-07-11 18:38 UTC
Hi! I'm trying to use the open-instruct code to finetune on a custom dataset. I was able to run the finetune code and save the model, but I encountered a size mismatch error at the last step `merge_lora.py`. Any advice on how I can work around this? Thanks in advance! 

The command I ran: 
```
python open_instruct/merge_lora.py --base_model_name_or_path meta-llama/Meta-Llama-3-8B --lora_model_name_or_path ../models/Meta-Llama-3-8B_qlora/ --output_dir ../models/Meta-Llama-3-8B_qlora_merged/ --qlora --save_tokenizer
```

Full terminal output: 
```
Loading the base model...
/home/jingjingl/.conda/envs/harm_project/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.19s/it]
Dequantizing `model.layers.0.self_attn.q_proj`...
Dequantizing `model.layers.0.self_attn.k_proj`...
Dequantizing `model.layers.0.self_attn.v_proj`...
Dequantizing `model.layers.0.self_attn.o_proj`...
Dequantizing `model.layers.0.mlp.gate_proj`...
Dequantizing `model.layers.0.mlp.up_proj`...
Dequantizing `model.layers.0.mlp.down_proj`...
Dequantizing `model.layers.1.self_attn.q_proj`...
Dequantizing `model.layers.1.self_attn.k_proj`...
Dequantizing `model.layers.1.self_attn.v_proj`...
Dequantizing `model.layers.1.self_attn.o_proj`...
Dequantizing `model.layers.1.mlp.gate_proj`...
Dequantizing `model.layers.1.mlp.up_proj`...
Dequantizing `model.layers.1.mlp.down_proj`...
Dequantizing `model.layers.2.self_attn.q_proj`...
Dequantizing `model.layers.2.self_attn.k_proj`...
Dequantizing `model.layers.2.self_attn.v_proj`...
Dequantizing `model.layers.2.self_attn.o_proj`...
Dequantizing `model.layers.2.mlp.gate_proj`...
Dequantizing `model.layers.2.mlp.up_proj`...
Dequantizing `model.layers.2.mlp.down_proj`...
Dequantizing `model.layers.3.self_attn.q_proj`...
Dequantizing `model.layers.3.self_attn.k_proj`...
Dequantizing `model.layers.3.self_attn.v_proj`...
Dequantizing `model.layers.3.self_attn.o_proj`...
Dequantizing `model.layers.3.mlp.gate_proj`...
Dequantizing `model.layers.3.mlp.up_proj`...
Dequantizing `model.layers.3.mlp.down_proj`...
Dequantizing `model.layers.4.self_attn.q_proj`...
Dequantizing `model.layers.4.self_attn.k_proj`...
Dequantizing `model.layers.4.self_attn.v_proj`...
Dequantizing `model.layers.4.self_attn.o_proj`...
Dequantizing `model.layers.4.mlp.gate_proj`...
Dequantizing `model.layers.4.mlp.up_proj`...
Dequantizing `model.layers.4.mlp.down_proj`...
Dequantizing `model.layers.5.self_attn.q_proj`...
Dequantizing `model.layers.5.self_attn.k_proj`...
Dequantizing `model.layers.5.self_attn.v_proj`...
Dequantizing `model.layers.5.self_attn.o_proj`...
Dequantizing `model.layers.5.mlp.gate_proj`...
Dequantizing `model.layers.5.mlp.up_proj`...
Dequantizing `model.layers.5.mlp.down_proj`...
Dequantizing `model.layers.6.self_attn.q_proj`...
Dequantizing `model.layers.6.self_attn.k_proj`...
Dequantizing `model.layers.6.self_attn.v_proj`...
Dequantizing `model.layers.6.self_attn.o_proj`...
Dequantizing `model.layers.6.mlp.gate_proj`...
Dequantizing `model.layers.6.mlp.up_proj`...
Dequantizing `model.layers.6.mlp.down_proj`...
Dequantizing `model.layers.7.self_attn.q_proj`...
Dequantizing `model.layers.7.self_attn.k_proj`...
Dequantizing `model.layers.7.self_attn.v_proj`...
Dequantizing `model.layers.7.self_attn.o_proj`...
Dequantizing `model.layers.7.mlp.gate_proj`...
Dequantizing `model.layers.7.mlp.up_proj`...
Dequantizing `model.layers.7.mlp.down_proj`...
Dequantizing `model.layers.8.self_attn.q_proj`...
Dequantizing `model.layers.8.self_attn.k_proj`...
Dequantizing `model.layers.8.self_attn.v_proj`...
Dequantizing `model.layers.8.self_attn.o_proj`...
Dequantizing `model.layers.8.mlp.gate_proj`...
Dequantizing `model.layers.8.mlp.up_proj`...
Dequantizing `model.layers.8.mlp.down_proj`...
Dequantizing `model.layers.9.self_attn.q_proj`...
Dequantizing `model.layers.9.self_attn.k_proj`...
Dequantizing `model.layers.9.self_attn.v_proj`...
Dequantizing `model.layers.9.self_attn.o_proj`...
Dequantizing `model.layers.9.mlp.gate_proj`...
Dequantizing `model.layers.9.mlp.up_proj`...
Dequantizing `model.layers.9.mlp.down_proj`...
Dequantizing `model.layers.10.self_attn.q_proj`...
Dequantizing `model.layers.10.self_attn.k_proj`...
Dequantizing `model.layers.10.self_attn.v_proj`...
Dequantizing `model.layers.10.self_attn.o_proj`...
Dequantizing `model.layers.10.mlp.gate_proj`...
Dequantizing `model.layers.10.mlp.up_proj`...
Dequantizing `model.layers.10.mlp.down_proj`...
Dequantizing `model.layers.11.self_attn.q_proj`...
Dequantizing `model.layers.11.self_attn.k_proj`...
Dequantizing `model.layers.11.self_attn.v_proj`...
Dequantizing `model.layers.11.self_attn.o_proj`...
Dequantizing `model.layers.11.mlp.gate_proj`...
Dequantizing `model.layers.11.mlp.up_proj`...
Dequantizing `model.layers.11.mlp.down_proj`...
Dequantizing `model.layers.12.self_attn.q_proj`...
Dequantizing `model.layers.12.self_attn.k_proj`...
Dequantizing `model.layers.12.self_attn.v_proj`...
Dequantizing `model.layers.12.self_attn.o_proj`...
Dequantizing `model.layers.12.mlp.gate_proj`...
Dequantizing `model.layers.12.mlp.up_proj`...
Dequantizing `model.layers.12.mlp.down_proj`...
Dequantizing `model.layers.13.self_attn.q_proj`...
Dequantizing `model.layers.13.self_attn.k_proj`...
Dequantizing `model.layers.13.self_attn.v_proj`...
Dequantizing `model.layers.13.self_attn.o_proj`...
Dequantizing `model.layers.13.mlp.gate_proj`...
Dequantizing `model.layers.13.mlp.up_proj`...
Dequantizing `model.layers.13.mlp.down_proj`...
Dequantizing `model.layers.14.self_attn.q_proj`...
Dequantizing `model.layers.14.self_attn.k_proj`...
Dequantizing `model.layers.14.self_attn.v_proj`...
Dequantizing `model.layers.14.self_attn.o_proj`...
Dequantizing `model.layers.14.mlp.gate_proj`...
Dequantizing `model.layers.14.mlp.up_proj`...
Dequantizing `model.layers.14.mlp.down_proj`...
Dequantizing `model.layers.15.self_attn.q_proj`...
Dequantizing `model.layers.15.self_attn.k_proj`...
Dequantizing `model.layers.15.self_attn.v_proj`...
Dequantizing `model.layers.15.self_attn.o_proj`...
Dequantizing `model.layers.15.mlp.gate_proj`...
Dequantizing `model.layers.15.mlp.up_proj`...
Dequantizing `model.layers.15.mlp.down_proj`...
Dequantizing `model.layers.16.self_attn.q_proj`...
Dequantizing `model.layers.16.self_attn.k_proj`...
Dequantizing `model.layers.16.self_attn.v_proj`...
Dequantizing `model.layers.16.self_attn.o_proj`...
Dequantizing `model.layers.16.mlp.gate_proj`...
Dequantizing `model.layers.16.mlp.up_proj`...
Dequantizing `model.layers.16.mlp.down_proj`...
Dequantizing `model.layers.17.self_attn.q_proj`...
Dequantizing `model.layers.17.self_attn.k_proj`...
Dequantizing `model.layers.17.self_attn.v_proj`...
Dequantizing `model.layers.17.self_attn.o_proj`...
Dequantizing `model.layers.17.mlp.gate_proj`...
Dequantizing `model.layers.17.mlp.up_proj`...
Dequantizing `model.layers.17.mlp.down_proj`...
Dequantizing `model.layers.18.self_attn.q_proj`...
Dequantizing `model.layers.18.self_attn.k_proj`...
Dequantizing `model.layers.18.self_attn.v_proj`...
Dequantizing `model.layers.18.self_attn.o_proj`...
Dequantizing `model.layers.18.mlp.gate_proj`...
Dequantizing `model.layers.18.mlp.up_proj`...
Dequantizing `model.layers.18.mlp.down_proj`...
Dequantizing `model.layers.19.self_attn.q_proj`...
Dequantizing `model.layers.19.self_attn.k_proj`...
Dequantizing `model.layers.19.self_attn.v_proj`...
Dequantizing `model.layers.19.self_attn.o_proj`...
Dequantizing `model.layers.19.mlp.gate_proj`...
Dequantizing `model.layers.19.mlp.up_proj`...
Dequantizing `model.layers.19.mlp.down_proj`...
Dequantizing `model.layers.20.self_attn.q_proj`...
Dequantizing `model.layers.20.self_attn.k_proj`...
Dequantizing `model.layers.20.self_attn.v_proj`...
Dequantizing `model.layers.20.self_attn.o_proj`...
Dequantizing `model.layers.20.mlp.gate_proj`...
Dequantizing `model.layers.20.mlp.up_proj`...
Dequantizing `model.layers.20.mlp.down_proj`...
Dequantizing `model.layers.21.self_attn.q_proj`...
Dequantizing `model.layers.21.self_attn.k_proj`...
Dequantizing `model.layers.21.self_attn.v_proj`...
Dequantizing `model.layers.21.self_attn.o_proj`...
Dequantizing `model.layers.21.mlp.gate_proj`...
Dequantizing `model.layers.21.mlp.up_proj`...
Dequantizing `model.layers.21.mlp.down_proj`...
Dequantizing `model.layers.22.self_attn.q_proj`...
Dequantizing `model.layers.22.self_attn.k_proj`...
Dequantizing `model.layers.22.self_attn.v_proj`...
Dequantizing `model.layers.22.self_attn.o_proj`...
Dequantizing `model.layers.22.mlp.gate_proj`...
Dequantizing `model.layers.22.mlp.up_proj`...
Dequantizing `model.layers.22.mlp.down_proj`...
Dequantizing `model.layers.23.self_attn.q_proj`...
Dequantizing `model.layers.23.self_attn.k_proj`...
Dequantizing `model.layers.23.self_attn.v_proj`...
Dequantizing `model.layers.23.self_attn.o_proj`...
Dequantizing `model.layers.23.mlp.gate_proj`...
Dequantizing `model.layers.23.mlp.up_proj`...
Dequantizing `model.layers.23.mlp.down_proj`...
Dequantizing `model.layers.24.self_attn.q_proj`...
Dequantizing `model.layers.24.self_attn.k_proj`...
Dequantizing `model.layers.24.self_attn.v_proj`...
Dequantizing `model.layers.24.self_attn.o_proj`...
Dequantizing `model.layers.24.mlp.gate_proj`...
Dequantizing `model.layers.24.mlp.up_proj`...
Dequantizing `model.layers.24.mlp.down_proj`...
Dequantizing `model.layers.25.self_attn.q_proj`...
Dequantizing `model.layers.25.self_attn.k_proj`...
Dequantizing `model.layers.25.self_attn.v_proj`...
Dequantizing `model.layers.25.self_attn.o_proj`...
Dequantizing `model.layers.25.mlp.gate_proj`...
Dequantizing `model.layers.25.mlp.up_proj`...
Dequantizing `model.layers.25.mlp.down_proj`...
Dequantizing `model.layers.26.self_attn.q_proj`...
Dequantizing `model.layers.26.self_attn.k_proj`...
Dequantizing `model.layers.26.self_attn.v_proj`...
Dequantizing `model.layers.26.self_attn.o_proj`...
Dequantizing `model.layers.26.mlp.gate_proj`...
Dequantizing `model.layers.26.mlp.up_proj`...
Dequantizing `model.layers.26.mlp.down_proj`...
Dequantizing `model.layers.27.self_attn.q_proj`...
Dequantizing `model.layers.27.self_attn.k_proj`...
Dequantizing `model.layers.27.self_attn.v_proj`...
Dequantizing `model.layers.27.self_attn.o_proj`...
Dequantizing `model.layers.27.mlp.gate_proj`...
Dequantizing `model.layers.27.mlp.up_proj`...
Dequantizing `model.layers.27.mlp.down_proj`...
Dequantizing `model.layers.28.self_attn.q_proj`...
Dequantizing `model.layers.28.self_attn.k_proj`...
Dequantizing `model.layers.28.self_attn.v_proj`...
Dequantizing `model.layers.28.self_attn.o_proj`...
Dequantizing `model.layers.28.mlp.gate_proj`...
Dequantizing `model.layers.28.mlp.up_proj`...
Dequantizing `model.layers.28.mlp.down_proj`...
Dequantizing `model.layers.29.self_attn.q_proj`...
Dequantizing `model.layers.29.self_attn.k_proj`...
Dequantizing `model.layers.29.self_attn.v_proj`...
Dequantizing `model.layers.29.self_attn.o_proj`...
Dequantizing `model.layers.29.mlp.gate_proj`...
Dequantizing `model.layers.29.mlp.up_proj`...
Dequantizing `model.layers.29.mlp.down_proj`...
Dequantizing `model.layers.30.self_attn.q_proj`...
Dequantizing `model.layers.30.self_attn.k_proj`...
Dequantizing `model.layers.30.self_attn.v_proj`...
Dequantizing `model.layers.30.self_attn.o_proj`...
Dequantizing `model.layers.30.mlp.gate_proj`...
Dequantizing `model.layers.30.mlp.up_proj`...
Dequantizing `model.layers.30.mlp.down_proj`...
Dequantizing `model.layers.31.self_attn.q_proj`...
Dequantizing `model.layers.31.self_attn.k_proj`...
Dequantizing `model.layers.31.self_attn.v_proj`...
Dequantizing `model.layers.31.self_attn.o_proj`...
Dequantizing `model.layers.31.mlp.gate_proj`...
Dequantizing `model.layers.31.mlp.up_proj`...
Dequantizing `model.layers.31.mlp.down_proj`...
Trying to load the tokenizer in the lora model folder...
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The vocabulary the tokenizer contains 1 more tokens than the base model.
Resizing the token embeddings of the merged model...
Loading the lora model...
Traceback (most recent call last):
  File "/home/jingjingl/interpret_harm/open-instruct/open_instruct/merge_lora.py", line 121, in <module>
    lora_model = PeftModel.from_pretrained(base_model, args.lora_model_name_or_path)
  File "/home/jingjingl/.conda/envs/harm_project/lib/python3.10/site-packages/peft/peft_model.py", line 430, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/home/jingjingl/.conda/envs/harm_project/lib/python3.10/site-packages/peft/peft_model.py", line 988, in load_adapter
    load_result = set_peft_model_state_dict(
  File "/home/jingjingl/.conda/envs/harm_project/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 353, in set_peft_model_state_dict
    load_result = model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/jingjingl/.conda/envs/harm_project/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([128264, 4096]) from checkpoint, the shape in current model is torch.Size([128257, 4096]).
	size mismatch for base_model.model.lm_head.weight: copying a param with shape torch.Size([128264, 4096]) from checkpoint, the shape in current model is torch.Size([128257, 4096]).
```

**Comment by hamishivi** [comment] 2024-07-12 21:05
We discussed on slack - I wasn't able to reproduce this (the resizing seemed to work normal out of the box), although I discovered an issue I've fixed in #191. I may have missed something in trying to reproduce, so if you hit this error again, or something similar, please feel free to re-open this issue!

**Closed by hamishivi** 2024-07-12 21:05 UTC

**Comment by amao0o0** [comment] 2024-08-29 07:09
Hi. I also encountered this issue. Wonder if you have solved this issue?

**Comment by hamishivi** [comment] 2024-08-29 15:39
Oh, nice catch! I updated the finetune script but didn't update the merge script (since I don't use it often). I'll push a fix.
